### ISSUE TITLE
Any commands result in the same error message (help,version,build...)

### ISSUE THREAD

**Issue by esloch** [osl-incubator/containers-sugar#12]
* containers-sugar version:
``` 
06:28 $ pip show containers-sugar
Name: containers-sugar
Version: 1.0.1
Summary: Simplify the usage of containers
Home-page: 
Author: Ivan Ogasawara
Author-email: ivan.ogasawara@gmail.com
License: BSD 3 Clause
Location: /workspace/virtualenv/mambaforge/envs/alertadengue/lib/python3.9/site-packages
Requires: docker-compose, podman-compose, pyyaml, sh, types-pyyaml
Required-by: 
``` 
* Python version:
``` 
06:30 $ python --version
Python 3.9.15
``` 
* Operating System:
``` 
06:30 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic
---
06:32 $ uname -r
5.19.0-29-generic
``` 
### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
06:26 $ containers-sugar build --group prod
Traceback (most recent call last):
  File "/workspace/virtualenv/mambaforge/envs/alertadengue/bin/containers-sugar", line 3, in <module>
    from containers_sugar.__main__ import app
  File "/workspace/repos/infodengue/AlertaDengue/containers-sugar/containers_sugar/__init__.py", line 9, in <module>
    from containers_sugar.sugar import Sugar  # noqa: F401
  File "/workspace/repos/infodengue/AlertaDengue/containers-sugar/containers_sugar/sugar.py", line 18, in <module>
    class Sugar:
  File "/workspace/repos/infodengue/AlertaDengue/containers-sugar/containers_sugar/sugar.py", line 32, in Sugar
    args: object | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by xmnlab** [comment]
This was an issue about union between datatypes that was not supported by this python version. It should be fixed now. Thanks for reporting that
